AWSTemplateFormatVersion: 2010-09-09
Description: |
  Setup the necessary roles to allow a CLI user to Push / Pull from account ECR repositories
Resources:
  ECRServicePowerUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: ECRServicePowerUserGroup
  ECRServicePowerUserRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "VisualEditor0",
                  "Effect": "Allow",
                  "Action": [
                      "ecr:PutImageTagMutability",
                      "ecr:StartImageScan",
                      "ecr:DescribeImageReplicationStatus",
                      "ecr:ListTagsForResource",
                      "ecr:UploadLayerPart",
                      "ecr:BatchDeleteImage",
                      "ecr:CreatePullThroughCacheRule",
                      "ecr:ListImages",
                      "ecr:BatchGetRepositoryScanningConfiguration",
                      "ecr:PutRegistryPolicy",
                      "ecr:GetRegistryScanningConfiguration",
                      "ecr:CompleteLayerUpload",
                      "ecr:TagResource",
                      "ecr:DescribeRepositories",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:ReplicateImage",
                      "ecr:GetLifecyclePolicy",
                      "ecr:GetRegistryPolicy",
                      "ecr:PutLifecyclePolicy",
                      "ecr:DescribeImageScanFindings",
                      "ecr:GetLifecyclePolicyPreview",
                      "ecr:CreateRepository",
                      "ecr:DescribeRegistry",
                      "ecr:PutImageScanningConfiguration",
                      "ecr:GetDownloadUrlForLayer",
                      "ecr:DescribePullThroughCacheRules",
                      "ecr:GetAuthorizationToken",
                      "ecr:PutRegistryScanningConfiguration",
                      "ecr:PutImage",
                      "ecr:BatchImportUpstreamImage",
                      "ecr:UntagResource",
                      "ecr:SetRepositoryPolicy",
                      "ecr:BatchGetImage",
                      "ecr:DescribeImages",
                      "ecr:StartLifecyclePolicyPreview",
                      "ecr:InitiateLayerUpload",
                      "ecr:GetRepositoryPolicy",
                      "ecr:PutReplicationConfiguration"
                  ],
                  "Resource": "*"
              }
          ]
        }
      PolicyName: ECRServicePowerUserPolicy
      Groups:
        - !Ref ECRServicePowerUserGroup