AWSTemplateFormatVersion: 2010-09-09
Description: A CloudFormation template to setup an ECS Cluster
Parameters:
  CapacityProviders:
    Description: The short name of one or more capacity providers to associate with the cluster.
    Type: CommaDelimitedList
  EnableContainerInsights:
    Type: String
    Description: Enable Container Insights 
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  EnvironmentStage:
    Type: String
    Description: Designates the environment stage of the associated AWS resource. (Optional)
    AllowedValues:
      - 'spike'
      - 'dev'
      - 'test'
      - 'pre-prod'
      - 'prod'
      - 'none'
    Default: 'none'
Conditions:
  EnableContainerInsightsCondition: !Equals
    - !Ref EnableContainerInsights
    - 'true'
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders: !Ref CapacityProviders
      ClusterName: !Sub '${AWS::StackName}-Cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: !If [EnableContainerInsightsCondition, 'enabled', 'disabled']
Outputs:
  Cluster:
    Description: Customer name
    Value: !Ref Cluster
    Export:
      Name: !Sub '${AWS::StackName}-Cluster'
  CusterArn:
    Description: Customer ARN
    Value: !GetAtt  Cluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CusterArn'