AWSTemplateFormatVersion: 2010-09-09
Description: |
  Estabish VPC Mount Points for the supplied EFS volume
Parameters:
  VPCStackName:
    Description: Name of the stack used to create the VPC environment.  Will be used for ImportValue calls.
    Type: String
  SubnetIDsExporttName:
    Description: Exported variables from the VPC creation stack.
    Type: CommaDelimitedList
  EFSStackName:
    Description: Name of the stack used to create the EFS volume.
    Type: String
  NumberOfSubnets:
    AllowedValues:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of subnets. This must match your selections in the list of Subnets below.
    Type: String 
  SecurityGroup:
    Description: Select the Amazon EFS security group.
    Type: String 
    Default: ''
  SecurityGroupStackName:
    Description: CF Stack that created the SG to associate with the mount target
    Type: String 
    Default: ''
  SecurityGroupStackExportVariableName:
    Description: Export Variable to be used for geting the SG ID from the SG Stack
    Type: String
    Default: SecurityGroupId
Conditions:
  NumberOfSubnets1:
      !Equals [ 1, !Ref NumberOfSubnets ]
  NumberOfSubnets2:
      !Equals [ 2, !Ref NumberOfSubnets ]
  NumberOfSubnets3:
      !Equals [ 3, !Ref NumberOfSubnets ]
  NumberOfSubnets4:
      !Equals [ 4, !Ref NumberOfSubnets ]
  NumberOfSubnets5:
      !Equals [ 5, !Ref NumberOfSubnets ]
  NumberOfSubnets6:
      !Equals [ 6, !Ref NumberOfSubnets ]
  Subnet0: !Or
    - !Condition NumberOfSubnets1
    - !Condition NumberOfSubnets2
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet1: !Or
    - !Condition NumberOfSubnets2
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet2: !Or
    - !Condition NumberOfSubnets3
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet3: !Or
    - !Condition NumberOfSubnets4
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet4: !Or
    - !Condition NumberOfSubnets5
    - !Condition NumberOfSubnets6
  Subnet5: !Condition NumberOfSubnets6
  SecurityGroupSuppliedCondition: !Not
    - !Equals ['', !Ref SecurityGroup]
  SecurityGroupStackSuppliedCondition: !Not
    - !Equals ['', !Ref SecurityGroupStackName]
  UseDefaultSecurityGroupCondition: !And
    - !Not
      - !Condition SecurityGroupSuppliedCondition
    - !Not
      - !Condition SecurityGroupStackSuppliedCondition
Resources:
  ElasticFileSystemMountTarget0:
    Condition: Subnet0
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Join [ "-", [ !Ref EFSStackName, "EFSFileSystem"]]
      SecurityGroups:
        - !If [ UseDefaultSecurityGroupCondition,  Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "DefaultSG"]],  !Ref AWS::NoValue ]
        - !If [ SecurityGroupSuppliedCondition,  !Ref SecurityGroup,  !Ref AWS::NoValue ]
        - !If [ SecurityGroupStackSuppliedCondition,  Fn::ImportValue: !Join [ "-", [ !Ref SecurityGroupStackName, "SecurityGroupId"]],  !Ref AWS::NoValue ]
      SubnetId: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, !Select [ 0, !Ref SubnetIDsExporttName ]]]
  ElasticFileSystemMountTarget1:
    Condition: Subnet1
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Join [ "-", [ !Ref EFSStackName, "EFSFileSystem"]]
      SecurityGroups:
        - !If [ UseDefaultSecurityGroupCondition,  Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "DefaultSG"]],  !Ref AWS::NoValue ]
        - !If [ SecurityGroupSuppliedCondition,  !Ref SecurityGroup,  !Ref AWS::NoValue ]
        - !If [ SecurityGroupStackSuppliedCondition,  Fn::ImportValue: !Join [ "-", [ !Ref SecurityGroupStackName, "SecurityGroupId"]],  !Ref AWS::NoValue ]
      SubnetId: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, !Select [ 1, !Ref SubnetIDsExporttName ]]]
  ElasticFileSystemMountTarget2:
    Condition: Subnet2
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Join [ "-", [ !Ref EFSStackName, "EFSFileSystem"]]
      SecurityGroups:
        - !If [ UseDefaultSecurityGroupCondition,  Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "DefaultSG"]],  !Ref AWS::NoValue ]
        - !If [ SecurityGroupSuppliedCondition,  !Ref SecurityGroup,  !Ref AWS::NoValue ]
        - !If [ SecurityGroupStackSuppliedCondition,  Fn::ImportValue: !Join [ "-", [ !Ref SecurityGroupStackName, "SecurityGroupId"]],  !Ref AWS::NoValue ]
      SubnetId: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, !Select [ 2, !Ref SubnetIDsExporttName ]]]
  ElasticFileSystemMountTarget3:
    Condition: Subnet3
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Join [ "-", [ !Ref EFSStackName, "EFSFileSystem"]]
      SecurityGroups:
        - !If [ UseDefaultSecurityGroupCondition,  Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "DefaultSG"]],  !Ref AWS::NoValue ]
        - !If [ SecurityGroupSuppliedCondition,  !Ref SecurityGroup,  !Ref AWS::NoValue ]
        - !If [ SecurityGroupStackSuppliedCondition,  Fn::ImportValue: !Join [ "-", [ !Ref SecurityGroupStackName, "SecurityGroupId"]],  !Ref AWS::NoValue ]
      SubnetId: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, !Select [ 3, !Ref SubnetIDsExporttName ]]]
  ElasticFileSystemMountTarget4:
    Condition: Subnet4
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Join [ "-", [ !Ref EFSStackName, "EFSFileSystem"]]
      SecurityGroups:
        - !If [ UseDefaultSecurityGroupCondition,  Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "DefaultSG"]],  !Ref AWS::NoValue ]
        - !If [ SecurityGroupSuppliedCondition,  !Ref SecurityGroup,  !Ref AWS::NoValue ]
        - !If [ SecurityGroupStackSuppliedCondition,  Fn::ImportValue: !Join [ "-", [ !Ref SecurityGroupStackName, "SecurityGroupId"]],  !Ref AWS::NoValue ]
      SubnetId: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, !Select [ 4, !Ref SubnetIDsExporttName ]]]
  ElasticFileSystemMountTarget5:
    Condition: Subnet5
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: 
        Fn::ImportValue: !Join [ "-", [ !Ref EFSStackName, "EFSFileSystem"]]
      SecurityGroups:
        - !If [ UseDefaultSecurityGroupCondition,  Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "DefaultSG"]],  !Ref AWS::NoValue ]
        - !If [ SecurityGroupSuppliedCondition,  !Ref SecurityGroup,  !Ref AWS::NoValue ]
        - !If [ SecurityGroupStackSuppliedCondition,  Fn::ImportValue: !Join [ "-", [ !Ref SecurityGroupStackName, "SecurityGroupId"]],  !Ref AWS::NoValue ]
      SubnetId: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, !Select [ 5, !Ref SubnetIDsExporttName ]]]