AWSTemplateFormatVersion: 2010-09-09
Description: An  CloudFormation template for building a Private DNS for Service Map.
Parameters:
  NamespaceDescription:
    Description: A description for the namespace.
    Type: String
    Default: ''
  DnsName:
    Description: The name that you want to assign to this namespace. When you create a private DNS namespace, AWS Cloud Map automatically creates an Amazon Route 53 private hosted zone that has the same name as the namespace.
    Type: String
  VPCStackName:
    Description: Name of the stack used to create the VPC
    Type: String
Resources:
  PrivateNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: !Ref NamespaceDescription
      Vpc: 
        Fn::ImportValue: !Join [ "-", [ !Ref VPCStackName, "VPCID"]]
      Name: !Ref DnsName

Outputs:
  NamespaceId: 
    Description: The Id of the Private Namespace
    Value: !Ref PrivateNamespace
    Export:
      Name: !Sub '${AWS::StackName}-NamespaceId'
  NamespaceArn: 
    Description: The ARN of the Private Namesapce
    Value: !GetAtt PrivateNamespace.Arn
    Export:
      Name: !Sub '${AWS::StackName}-NamespaceArn'
