AWSTemplateFormatVersion: 2010-09-09
Description: An CloudFormation template to create a Secret
Parameters:
  Name:
    Type: String
    Description: The friendly name of the secret.
  Description:
    Type: String
    Description: Specifies a user-provided description of the secret.
    Default: ''
  SecretString:
    Type: String 
    Description: Specifies text data that you want to encrypt and store in this new version of the secret.
Conditions:
  HasDescriptionCondition: !Not
    - !Equals
      - !Ref Description
      - ''
Resources:
  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-${Name}'
      Description: !If 
        - HasDescriptionCondition
        - !Ref Description
        - !Ref AWS::NoValue
      SecretString: !Ref SecretString
Outputs:
  SecretArn:
    Description: The ARN of the secret
    Value: !Ref Secret
    Export:
      Name: !Sub '${AWS::StackName}-SecretArn'