AWSTemplateFormatVersion: 2010-09-09
Description: An CloudFormation template to create a Secret with optional CMK

Parameters:
  Name:
    Type: String
    Description: The friendly name of the secret.
  Description:
    Type: String
    Description: Specifies a user-provided description of the secret.
    Default: ''
  SecretString:
    Type: String
    Description: Specifies text data that you want to encrypt and store in this new version of the secret.
  CreateCMK:
    Type: String
    Description: Whether to create a new CMK for encryption (true or false).
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  HasDescriptionCondition: !Not [!Equals [!Ref Description, '']]
  CreateCMKCondition: !Equals [!Ref CreateCMK, 'true']

Resources:
  # Conditionally create the CMK
  Key:
    Type: AWS::KMS::Key
    Condition: CreateCMKCondition
    Properties:
      Description: !Sub '${AWS::StackName}-${Name}-Key'
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'

  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-${Name}'
      Description: !If [HasDescriptionCondition, !Ref Description, !Ref AWS::NoValue]
      SecretString: !Ref SecretString
      KmsKeyId: !If [CreateCMKCondition, !GetAtt Key.Arn, !Ref AWS::NoValue]

Outputs:
  SecretArn:
    Description: The ARN of the secret
    Value: !Ref Secret
    Export:
      Name: !Sub '${AWS::StackName}-SecretArn'
